// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNELR-OaqHS4YPp6EEZZBbLhma2JSf7JE',
    appId: '1:562461045714:web:26c4e8846cff8d34838e0b',
    messagingSenderId: '562461045714',
    projectId: 'adoppet-98cf3',
    authDomain: 'adoppet-98cf3.firebaseapp.com',
    storageBucket: 'adoppet-98cf3.appspot.com',
    measurementId: 'G-KKWYT0XDZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2aUJ_3E4C5TtUKXm1fF-3b5R1RQ74GgI',
    appId: '1:562461045714:android:8139b9ce0b8874ec838e0b',
    messagingSenderId: '562461045714',
    projectId: 'adoppet-98cf3',
    storageBucket: 'adoppet-98cf3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSiTUKZ2dLkzqkNeFeFeKatgJrq68CdUo',
    appId: '1:562461045714:ios:a2744d6f189e971d838e0b',
    messagingSenderId: '562461045714',
    projectId: 'adoppet-98cf3',
    storageBucket: 'adoppet-98cf3.appspot.com',
    iosClientId: '562461045714-5upg6e9sd7ejc0en7d3okrg7se9pv658.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSiTUKZ2dLkzqkNeFeFeKatgJrq68CdUo',
    appId: '1:562461045714:ios:ea2cc8105cc9a06c838e0b',
    messagingSenderId: '562461045714',
    projectId: 'adoppet-98cf3',
    storageBucket: 'adoppet-98cf3.appspot.com',
    iosClientId: '562461045714-efe20lnq79e2mk786hv8k6rgaci6nnng.apps.googleusercontent.com',
    iosBundleId: 'com.example.adoptMe.RunnerTests',
  );
}
